include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    dead_code: error
    invalid_use_of_protected_member: error
    invalid_use_of_visible_for_testing_member: error
    missing_required_param: error
    missing_return: error
